# frozen_string_literal: true

source 'https://rubygems.org'

ruby file: '.ruby-version'

group :test do
  gem 'prop_check'
  gem 'rspec-parameterized'
end

group :development do
  gem 'rubocop', '1.74.0'
end
